### ISSUE TITLE
Create And Develop "Skeleton" 

### ISSUE THREAD

**Issue by bradennatali** [elindstr/mlb-app#2]
Create and develop the skeleton for the web application. 

Code the HTML

Design folder to be intuitive (HTML, CSS, JS, folders)

Develop web page to have these basics in HTML/CSS

**include placeholder text

- [x]  Nav (title) Bar
- [x]  Search bar
- [x]  Player Card Area (Duel)
- [x]  Player List Area
- [x]  Favorite Team Area
- [x]  Other Stats Area

**Comment by elindstr** [comment]
Done
