### ISSUE TITLE
design player cards  

### ISSUE THREAD

**Issue by elindstr** [elindstr/mlb-app#23]
* decide what stats should be displayed on player items in secondary and featured sections
* design layout
* you can use placeholder stats and Eric will fill in the API linkage

**Comment by elindstr** [comment]
The featured slash table is generated by cardStats.js starting at line 41. Probably the data should be swapped to be in column rather than row format. And probably rather than an inflexible <table> the data should be rendered as elements in a flex display.

The secondary player items have white space. Maybe this white space could be filled with some stats?

**Comment by JakeHigham** [comment]
Stats to be displayed

ERA/WHIP/K:BB slashline pitching
BA/OBP/SLUGGING slashline hitting

**Comment by JakeHigham** [comment]
![playercard](https://github.com/elindstr/slash-line-stats/assets/149442786/9a443956-2419-460b-9803-eb4657fc2f85)


So, just a basic 3 stat slash-line

**Comment by JakeHigham** [comment]
![image](https://github.com/elindstr/slash-line-stats/assets/149442786/363f0e79-4ab3-409d-b911-df57b9481893)


Current working design
