### ISSUE TITLE
JavaScript / JQuery

### ISSUE THREAD

**Issue by bradennatali** [elindstr/mlb-app#6]
Help integrate javascript with CSS and API data 

- [x] Build Fetch Requests for API data
- [x] Build Event Listeners for buttons
- [x] Develop functionality for API Data to be displayed in Search Bar drop down
- [x] Develop functionality for sorting, deleting, and adding new cards to Player List
- [x] Use Jquery to develop "drag" functionality from list to 'duel' area
- [x] Develop functionality for API information to be displayed on page
- [x] Build Code within Jquery to develop a player list that condenses when player is not selected in "duel" area
- [ ]

**Comment by elindstr** [comment]
Done
